- name: add Rust plugin to asdf
  command:
    cmd: "{{ user_home_directory }}/.asdf/bin/asdf plugin-add rust https://github.com/code-lever/asdf-rust.git"
    creates: "{{ user_home_directory }}/.asdf/plugins/rust/bin/install"
  register: rust_add
  failed_when: rust_add == 2

- name: install Rust versions
  command:
    cmd: "{{ user_home_directory }}/.asdf/bin/asdf install rust {{ item }}"
    creates: "{{ user_home_directory }}/.asdf/installs/rust/{{ item }}/bin/cargo"
  loop: "{{ versions }}"

- name: check if global Rust version is v{{ global_version }}
  shell: asdf current rust | grep {{ global_version }}
  register: rust_global_version
  changed_when: no
  ignore_errors: yes

- name: set global version for Rust to v{{ global_version }}
  command: "{{ user_home_directory }}/.asdf/bin/asdf global rust {{ global_version }}"
  when: rust_global_version.rc > 0
