- name: add Golang plugin to asdf
  command:
    cmd: asdf plugin-add golang https://github.com/kennyp/asdf-golang.git
    creates: "{{ user_home_directory }}/.asdf/plugins/golang/bin/install"
  register: golang_add
  failed_when: golang_add == 2

- name: install Golang versions
  command:
    cmd: asdf install golang {{ item }}
    creates: "{{ user_home_directory }}/.asdf/installs/golang/{{ item }}/go/bin/go"
  loop: "{{ versions }}"

- name: check if global Golang version is v{{ global_version }}
  shell: asdf current golang | grep {{ global_version }}
  register: golang_global_version
  changed_when: no
  ignore_errors: yes

- name: set global version for Golang to v{{ global_version }}
  command: asdf global golang {{ global_version }}
  when: golang_global_version.rc > 0
