version: "3"

networks:
  kafka:
    driver: bridge

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
     - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    ports:
      - 9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

  opa:
    image: openpolicyagent/opa
    ports:
      - 8181:8181
    command:
      - run
      - --server
      - --log-level=debug

  email.mailcatcher:
    image: schickling/mailcatcher:latest
    restart: always
    ports:
      - 1025:1025
      - 1080:1080

  database.postgis:
    image: mdillon/postgis:latest
    restart: always
    ports:
      - 5433:5432
    env_file:
      - ./services/database/postgis/.env
    volumes:
      - ./volumes/postgis:/var/lib/postgresql/data

  database.postgresql:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./services/database/postgresql/.env
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data

  database.dynamodb:
    image: amazon/dynamodb-local:latest
    restart: always
    ports:
      - 8000:8000

  database.redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379

  database.memcached:
    image: memcached:latest
    restart: always
    ports:
      - 11211:11211

  database.mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
