- name: link global .default-python-packages file
  file:
    src: "{{ dotfiles_directory }}/roles/python/files/default-python-packages.symlink"
    dest: "{{ user_home_directory }}/.default-python-packages"
    state: link

- name: add Python plugin to asdf
  command:
    cmd: "{{ user_home_directory }}/.asdf/bin/asdf plugin-add python https://github.com/danhper/asdf-python"
    creates: "{{ user_home_directory }}/.asdf/plugins/python/bin/install"
  register: python_add
  failed_when: python_add == 2

- name: install Python versions
  command:
    cmd: "{{ user_home_directory }}/.asdf/bin/asdf install python {{ item }}"
    creates: "{{ user_home_directory }}/.asdf/installs/python/{{ item }}/bin/python"
  loop: "{{ versions }}"

- name: check if global Python version is v{{ global_version }}
  shell: "{{ user_home_directory }}/.asdf/bin/asdf current python | grep {{ global_version }}"
  register: python_global_version
  changed_when: no
  ignore_errors: yes

- name: set global version for Python to v{{ global_version }}
  command: "{{ user_home_directory }}/.asdf/bin/asdf global python {{ global_version }}"
  when: python_global_version.rc > 0
