version: "3"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: unless-stopped
    ports:
      - 9000:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - 9001:3000

  minio:
    image: minio/minio:edge
    command:
      - server
      - /data
    restart: unless-stopped
    ports:
      - 9002:9000
    volumes:
      - "./volumes/minio/storage:/data"
    env_file:
      - ./services/minio/.env

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - 9090:9090

  verdaccio:
    image: verdaccio/verdaccio:latest
    restart: unless-stopped
    ports:
      - 4873:4873
    volumes:
      - "./volumes/verdaccio/storage:/verdaccio/storage"
      - "./volumes/verdaccio/plugins:/verdaccio/plugins"
    environment:
      - VERDACCIO_PORT=4873

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: unless-stopped
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: unless-stopped
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  opa:
    image: openpolicyagent/opa:latest
    restart: unless-stopped
    ports:
      - 8181:8181
    command:
      - run
      - --server
      - --log-level=debug

  email.mailcatcher:
    image: schickling/mailcatcher:latest
    restart: unless-stopped
    ports:
      - 1025:1025
      - 1080:1080

  database.eventstore:
    image: eventstore/eventstore:latest
    restart: unless-stopped
    ports:
      - 2113:2113
      - 1113:1113

  database.postgis:
    image: mdillon/postgis:latest
    restart: unless-stopped
    ports:
      - 5433:5432
    env_file:
      - ./services/database/postgis/.env
    volumes:
      - ./volumes/postgis:/var/lib/postgresql/data

  database.postgresql:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - ./services/database/postgresql/.env
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data

  database.dynamodb:
    image: amazon/dynamodb-local:latest
    restart: unless-stopped
    ports:
      - 8000:8000

  database.redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379

  database.memcached:
    image: memcached:latest
    restart: unless-stopped
    ports:
      - 11211:11211

  database.mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
