- name: link .gitignore_global file
  file:
    src: "{{ dotfiles_directory }}/roles/git/files/gitignore_global.symlink"
    dest: "{{ user_home_directory }}/.gitignore_global"
    state: link
    force: yes

- name: link .gitconfig file
  file:
    src: "{{ dotfiles_directory }}/roles/git/files/gitconfig.symlink"
    dest: "{{ user_home_directory }}/.gitconfig"
    state: link
    force: yes

- name: link git-prompt.sh file
  file:
    src: "{{ dotfiles_directory }}/roles/git/files/git-prompt.symlink"
    dest: "{{ user_home_directory }}/git-prompt.sh"
    state: link
    force: yes