- name: add Deno plugin to asdf
  command:
    cmd: "{{ user_home_directory }}/.asdf/bin/asdf plugin-add deno https://github.com/asdf-community/asdf-deno.git"
    creates: "{{ user_home_directory }}/.asdf/plugins/deno/bin/install"
  register: deno_add
  failed_when: deno_add == 2

- name: install Deno versions
  command:
    cmd: "{{ user_home_directory }}/.asdf/bin/asdf install deno {{ item }}"
    creates: "{{ user_home_directory }}/.asdf/installs/deno/{{ item }}/bin/deno"
  loop: "{{ versions }}"

- name: check if global Deno version is v{{ global_version }}
  shell: "{{ user_home_directory }}/.asdf/bin/asdf current deno | grep {{ global_version }}"
  register: deno_global_version
  changed_when: no
  ignore_errors: yes

- name: set global version for Deno to v{{ global_version }}
  command: "{{ user_home_directory }}/.asdf/bin/asdf global deno {{ global_version }}"
  when: deno_global_version.rc > 0
