- name: link global .default-gems file
  file:
    src: "{{ dotfiles_directory }}/roles/ruby/files/default-gems.symlink"
    dest: "{{ user_home_directory }}/.default-gems.symlink"
    state: link

- name: add Ruby plugin to asdf
  command:
    cmd: "{{ user_home_directory }}/.asdf/bin/asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby"
    creates: "{{ user_home_directory }}/.asdf/plugins/ruby/bin/install"
  register: ruby_add
  failed_when: ruby_add == 2

- name: install Ruby versions
  command:
    cmd: "{{ user_home_directory }}/.asdf/bin/asdf install ruby {{ item }}"
    creates: "{{ user_home_directory }}/.asdf/installs/ruby/{{ item }}/bin/ruby"
  loop: "{{ versions }}"

- name: check if global Ruby version is v{{ global_version }}
  shell: "{{ user_home_directory }}/.asdf/bin/asdf current ruby | grep {{ global_version }}"
  register: ruby_global_version
  changed_when: no
  ignore_errors: yes

- name: set global version for Ruby to v{{ global_version }}
  command: "{{ user_home_directory }}/.asdf/bin/asdf global ruby {{ global_version }}"
  when: ruby_global_version.rc > 0
